//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHomeWeb.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptFriendRequestButton {
            get {
                return ResourceManager.GetString("AcceptFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location has been registered!.
        /// </summary>
        public static string AddedLocationMessage {
            get {
                return ResourceManager.GetString("AddedLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been created. Thanks for registering!.
        /// </summary>
        public static string AddedPersonMessage {
            get {
                return ResourceManager.GetString("AddedPersonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string AddFriendButton {
            get {
                return ResourceManager.GetString("AddFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add people to your friends list!.
        /// </summary>
        public static string AddFriendExplanation {
            get {
                return ResourceManager.GetString("AddFriendExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to send friend requests..
        /// </summary>
        public static string AddFriendNotAuthenticatedText {
            get {
                return ResourceManager.GetString("AddFriendNotAuthenticatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a friend.
        /// </summary>
        public static string AddFriendTitle {
            get {
                return ResourceManager.GetString("AddFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a location to your profile.
        /// </summary>
        public static string AddHasLocationPageTitle {
            get {
                return ResourceManager.GetString("AddHasLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register location.
        /// </summary>
        public static string AddLocationButtonText {
            get {
                return ResourceManager.GetString("AddLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to register a location..
        /// </summary>
        public static string AddLocationNotAuthenticatedText {
            get {
                return ResourceManager.GetString("AddLocationNotAuthenticatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new location..
        /// </summary>
        public static string AddLocationPageDescription {
            get {
                return ResourceManager.GetString("AddLocationPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register location.
        /// </summary>
        public static string AddLocationPageTitle {
            get {
                return ResourceManager.GetString("AddLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        public static string AddPersonButtonText {
            get {
                return ResourceManager.GetString("AddPersonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AddPersonPageTitle {
            get {
                return ResourceManager.GetString("AddPersonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sensor.
        /// </summary>
        public static string AddSensor {
            get {
                return ResourceManager.GetString("AddSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a sensor.
        /// </summary>
        public static string AddSensorPageTitle {
            get {
                return ResourceManager.GetString("AddSensorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in to add a tag..
        /// </summary>
        public static string AddTagNotAuthenticated {
            get {
                return ResourceManager.GetString("AddTagNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag to a sensor.
        /// </summary>
        public static string AddTagPageTitle {
            get {
                return ResourceManager.GetString("AddTagPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin pages.
        /// </summary>
        public static string AdminPagesTitle {
            get {
                return ResourceManager.GetString("AdminPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All friends.
        /// </summary>
        public static string AllFriendsLabel {
            get {
                return ResourceManager.GetString("AllFriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages.
        /// </summary>
        public static string AllMessagesTitle {
            get {
                return ResourceManager.GetString("AllMessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birth date could not be parsed. Have you tried formatting it as &apos;YYYY/MM/DD&apos;?.
        /// </summary>
        public static string BadlyFormattedBirthDateError {
            get {
                return ResourceManager.GetString("BadlyFormattedBirthDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a location.
        /// </summary>
        public static string DashboardAddLocation {
            get {
                return ResourceManager.GetString("DashboardAddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your profile..
        /// </summary>
        public static string DashboardAddLocationPost {
            get {
                return ResourceManager.GetString("DashboardAddLocationPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you should.
        /// </summary>
        public static string DashboardAddLocationPre {
            get {
                return ResourceManager.GetString("DashboardAddLocationPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string DashboardCompareButtonLabel {
            get {
                return ResourceManager.GetString("DashboardCompareButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string DashboardGroupButtonLabel {
            get {
                return ResourceManager.GetString("DashboardGroupButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DashboardSensorSelectAllLabel {
            get {
                return ResourceManager.GetString("DashboardSensorSelectAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DashboardSensorSelectNoneLabel {
            get {
                return ResourceManager.GetString("DashboardSensorSelectNoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string DashboardSensorSelectToggleLabel {
            get {
                return ResourceManager.GetString("DashboardSensorSelectToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string DashboardStackButtonLabel {
            get {
                return ResourceManager.GetString("DashboardStackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string DashboardSumButtonLabel {
            get {
                return ResourceManager.GetString("DashboardSumButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited sensor!.
        /// </summary>
        public static string EditedSensorSuccess {
            get {
                return ResourceManager.GetString("EditedSensorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        public static string EditLocationButtonText {
            get {
                return ResourceManager.GetString("EditLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        public static string EditLocationPageTitle {
            get {
                return ResourceManager.GetString("EditLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited location!.
        /// </summary>
        public static string EditLocationSuccess {
            get {
                return ResourceManager.GetString("EditLocationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditPersonButtonText {
            get {
                return ResourceManager.GetString("EditPersonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile.
        /// </summary>
        public static string EditPersonPageTitle {
            get {
                return ResourceManager.GetString("EditPersonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sensor.
        /// </summary>
        public static string EditSensorButtonText {
            get {
                return ResourceManager.GetString("EditSensorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this Sensor.
        /// </summary>
        public static string EditSensorPageTitle {
            get {
                return ResourceManager.GetString("EditSensorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse &apos;{0}&apos; as a floating-point number..
        /// </summary>
        public static string ElectricityPriceParseError {
            get {
                return ResourceManager.GetString("ElectricityPriceParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems kind of lonely in here..
        /// </summary>
        public static string EmptyDashboardTitle {
            get {
                return ResourceManager.GetString("EmptyDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names must be non-empty..
        /// </summary>
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be non-empty..
        /// </summary>
        public static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames must be non-empty..
        /// </summary>
        public static string EmptyUserNameError {
            get {
                return ResourceManager.GetString("EmptyUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request accepted..
        /// </summary>
        public static string FriendRequestAccepted {
            get {
                return ResourceManager.GetString("FriendRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has sent you a friend request..
        /// </summary>
        public static string FriendRequestReceived {
            get {
                return ResourceManager.GetString("FriendRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request sent..
        /// </summary>
        public static string FriendRequestSent {
            get {
                return ResourceManager.GetString("FriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsPageTitle {
            get {
                return ResourceManager.GetString("FriendsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend&apos;s username.
        /// </summary>
        public static string FriendUsernameLabel {
            get {
                return ResourceManager.GetString("FriendUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string GraphTitle {
            get {
                return ResourceManager.GetString("GraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pretty graph, that, for reasons unknown, won&apos;t render..
        /// </summary>
        public static string GraphWontShow {
            get {
                return ResourceManager.GetString("GraphWontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t a member of any groups yet. Click the button above to make one!.
        /// </summary>
        public static string GroupOverviewNoGroups {
            get {
                return ResourceManager.GetString("GroupOverviewNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupOverviewPageTitle {
            get {
                return ResourceManager.GetString("GroupOverviewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from &lt;a href=&quot;/person/{0}&quot;&gt;{1}&lt;/a&gt; to &lt;a href=&quot;/person/{2}&quot;&gt;{3}&lt;/a&gt;.
        /// </summary>
        public static string GroupPostHeader {
            get {
                return ResourceManager.GetString("GroupPostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no posts yet by or to users in {0}..
        /// </summary>
        public static string GroupProfileNoPosts {
            get {
                return ResourceManager.GetString("GroupProfileNoPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group: {0}.
        /// </summary>
        public static string GroupProfilePageTitle {
            get {
                return ResourceManager.GetString("GroupProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidLoginError {
            get {
                return ResourceManager.GetString("InvalidLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pre-existing location called &apos;{0}&apos;..
        /// </summary>
        public static string LocationAlreadyExistsError {
            get {
                return ResourceManager.GetString("LocationAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location does not exist..
        /// </summary>
        public static string LocationDoesNotExist {
            get {
                return ResourceManager.GetString("LocationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity price, in $/kWh.
        /// </summary>
        public static string LocationElectricityPriceLabel {
            get {
                return ResourceManager.GetString("LocationElectricityPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string LocationNameLabel {
            get {
                return ResourceManager.GetString("LocationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner GUID.
        /// </summary>
        public static string LocationOwnerGuidLabel {
            get {
                return ResourceManager.GetString("LocationOwnerGuidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string LocationOwnerLabel {
            get {
                return ResourceManager.GetString("LocationOwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage locations.
        /// </summary>
        public static string LocationsAdminPageTitle {
            get {
                return ResourceManager.GetString("LocationsAdminPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationsPageTitle {
            get {
                return ResourceManager.GetString("LocationsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make report for selected users.
        /// </summary>
        public static string MakeReportLabel {
            get {
                return ResourceManager.GetString("MakeReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string MeasurementsPageTitle {
            get {
                return ResourceManager.GetString("MeasurementsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string MessageComposerBodyLabel {
            get {
                return ResourceManager.GetString("MessageComposerBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string MessageComposerTitle {
            get {
                return ResourceManager.GetString("MessageComposerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string MessageComposerToLabel {
            get {
                return ResourceManager.GetString("MessageComposerToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wrote:.
        /// </summary>
        public static string MessageHeader {
            get {
                return ResourceManager.GetString("MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string MessageIDLabel {
            get {
                return ResourceManager.GetString("MessageIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageMessageLabel {
            get {
                return ResourceManager.GetString("MessageMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string MessageRecipientLabel {
            get {
                return ResourceManager.GetString("MessageRecipientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string MessageSenderLabel {
            get {
                return ResourceManager.GetString("MessageSenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent..
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfileTitle {
            get {
                return ResourceManager.GetString("MyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New friend requests.
        /// </summary>
        public static string NewFriendRequestsLabel {
            get {
                return ResourceManager.GetString("NewFriendRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NewGroupDescriptionLabel {
            get {
                return ResourceManager.GetString("NewGroupDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string NewGroupNameLabel {
            get {
                return ResourceManager.GetString("NewGroupNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your news feed is empty..
        /// </summary>
        public static string NewsfeedNoMessages {
            get {
                return ResourceManager.GetString("NewsfeedNoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        public static string NewsfeedPageTitle {
            get {
                return ResourceManager.GetString("NewsfeedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message on {0}&apos;s wall.
        /// </summary>
        public static string NewWallPostLabel {
            get {
                return ResourceManager.GetString("NewWallPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no friends :(.
        /// </summary>
        public static string NoFriends {
            get {
                return ResourceManager.GetString("NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new friend requests..
        /// </summary>
        public static string NoNewFriendRequests {
            get {
                return ResourceManager.GetString("NoNewFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending friend requests..
        /// </summary>
        public static string NoPendingFriendRequests {
            get {
                return ResourceManager.GetString("NoPendingFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for that sensor or period.
        /// </summary>
        public static string NoSensorData {
            get {
                return ResourceManager.GetString("NoSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a different time period using the input above, or select a different sensor from the list on the right..
        /// </summary>
        public static string NoSensorDataHelpText {
            get {
                return ResourceManager.GetString("NoSensorDataHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sensor selected.
        /// </summary>
        public static string NoSensorSelected {
            get {
                return ResourceManager.GetString("NoSensorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sensor from the list on the right..
        /// </summary>
        public static string NoSensorSelectedHelpText {
            get {
                return ResourceManager.GetString("NoSensorSelectedHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags.
        /// </summary>
        public static string NoTagsText {
            get {
                return ResourceManager.GetString("NoTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you entered did not match..
        /// </summary>
        public static string PasswordMismatchError {
            get {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string PasswordPlease {
            get {
                return ResourceManager.GetString("PasswordPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending friend requests.
        /// </summary>
        public static string PendingFriendRequestsLabel {
            get {
                return ResourceManager.GetString("PendingFriendRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PersonAddressLabel {
            get {
                return ResourceManager.GetString("PersonAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken. ಠ_ಠ.
        /// </summary>
        public static string PersonAlreadyExistsError {
            get {
                return ResourceManager.GetString("PersonAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string PersonBirthdateLabel {
            get {
                return ResourceManager.GetString("PersonBirthdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of residence.
        /// </summary>
        public static string PersonCityLabel {
            get {
                return ResourceManager.GetString("PersonCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string PersonGUIDLabel {
            get {
                return ResourceManager.GetString("PersonGUIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PersonNameLabel {
            get {
                return ResourceManager.GetString("PersonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string PersonNewPasswordLabel {
            get {
                return ResourceManager.GetString("PersonNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PersonPasswordLabel {
            get {
                return ResourceManager.GetString("PersonPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string PersonRepeatNewPasswordLabel {
            get {
                return ResourceManager.GetString("PersonRepeatNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string PersonRepeatPasswordLabel {
            get {
                return ResourceManager.GetString("PersonRepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string PersonUserNameLabel {
            get {
                return ResourceManager.GetString("PersonUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string PersonZipCodeLabel {
            get {
                return ResourceManager.GetString("PersonZipCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a location:.
        /// </summary>
        public static string PickALocation {
            get {
                return ResourceManager.GetString("PickALocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a sensor.
        /// </summary>
        public static string PickASensor {
            get {
                return ResourceManager.GetString("PickASensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name to save the graph as..
        /// </summary>
        public static string PleaseEnterAName {
            get {
                return ResourceManager.GetString("PleaseEnterAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not logged in.\nPlease log in to continue..
        /// </summary>
        public static string PleaseLogIn {
            get {
                return ResourceManager.GetString("PleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated!.
        /// </summary>
        public static string ProfileEditSuccess {
            get {
                return ResourceManager.GetString("ProfileEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range select.
        /// </summary>
        public static string RangeSelectorTitle {
            get {
                return ResourceManager.GetString("RangeSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to save the graph.\nMaybe you  already have a graph with this name?.
        /// </summary>
        public static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a user.
        /// </summary>
        public static string SearchUserTitle {
            get {
                return ResourceManager.GetString("SearchUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} a friend request.
        /// </summary>
        public static string SendFriendRequestButton {
            get {
                return ResourceManager.GetString("SendFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to send messages..
        /// </summary>
        public static string SendMessageNotAuthenticatedText {
            get {
                return ResourceManager.GetString("SendMessageNotAuthenticatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor &apos;{0}&apos; added!.
        /// </summary>
        public static string SensorAdded {
            get {
                return ResourceManager.GetString("SensorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SensorDescriptionLabel {
            get {
                return ResourceManager.GetString("SensorDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That sensor does not exist..
        /// </summary>
        public static string SensorDoesNotExistError {
            get {
                return ResourceManager.GetString("SensorDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SensorIDLabel {
            get {
                return ResourceManager.GetString("SensorIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SensorLocationLabel {
            get {
                return ResourceManager.GetString("SensorLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SensorNameLabel {
            get {
                return ResourceManager.GetString("SensorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string SensorNotesLabel {
            get {
                return ResourceManager.GetString("SensorNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage sensors.
        /// </summary>
        public static string SensorsAdminPageTitle {
            get {
                return ResourceManager.GetString("SensorsAdminPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor select.
        /// </summary>
        public static string SensorSelectorTitle {
            get {
                return ResourceManager.GetString("SensorSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My sensors.
        /// </summary>
        public static string Sensorsfromuser {
            get {
                return ResourceManager.GetString("Sensorsfromuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsPageTitle {
            get {
                return ResourceManager.GetString("SensorsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string SensorTagsLabel {
            get {
                return ResourceManager.GetString("SensorTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved graph.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag added!.
        /// </summary>
        public static string TagAdded {
            get {
                return ResourceManager.GetString("TagAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged as.
        /// </summary>
        public static string TaggedAsLabel {
            get {
                return ResourceManager.GetString("TaggedAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string TagNameLabel {
            get {
                return ResourceManager.GetString("TagNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag select.
        /// </summary>
        public static string TagSelectorTitle {
            get {
                return ResourceManager.GetString("TagSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        public static string TimeLast30Days {
            get {
                return ResourceManager.GetString("TimeLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 365 days.
        /// </summary>
        public static string TimeLast365Days {
            get {
                return ResourceManager.GetString("TimeLast365Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string TimeLast7Days {
            get {
                return ResourceManager.GetString("TimeLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string TimeThisMonth {
            get {
                return ResourceManager.GetString("TimeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string TimeThisYear {
            get {
                return ResourceManager.GetString("TimeThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TimeToday {
            get {
                return ResourceManager.GetString("TimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolSelectorTitle {
            get {
                return ResourceManager.GetString("ToolSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated total price of electricity.
        /// </summary>
        public static string TotalElectricityPrice {
            get {
                return ResourceManager.GetString("TotalElectricityPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adding friends by searching through the users page!.
        /// </summary>
        public static string TryAddingFriends {
            get {
                return ResourceManager.GetString("TryAddingFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sensor.
        /// </summary>
        public static string UpdateSensorLabel {
            get {
                return ResourceManager.GetString("UpdateSensorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user does not exist..
        /// </summary>
        public static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find your username in the database..
        /// </summary>
        public static string UserNameNotFoundError {
            get {
                return ResourceManager.GetString("UserNameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string UsersAdminPageTitle {
            get {
                return ResourceManager.GetString("UsersAdminPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to view your friends..
        /// </summary>
        public static string ViewFriendsNotLoggedInError {
            get {
                return ResourceManager.GetString("ViewFriendsNotLoggedInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user&apos;s wall is empty!.
        /// </summary>
        public static string WallNoMessages {
            get {
                return ResourceManager.GetString("WallNoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Wall.
        /// </summary>
        public static string WallPageTitle {
            get {
                return ResourceManager.GetString("WallPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/person/{0}&quot;&gt;{1}&lt;/a&gt; wrote:.
        /// </summary>
        public static string WallPostHeader {
            get {
                return ResourceManager.GetString("WallPostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log, track, and organize your devices&apos; electricity usage. Create graphs of aggregated data and share them with friends..
        /// </summary>
        public static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string WelcomeCreateAccountButton {
            get {
                return ResourceManager.GetString("WelcomeCreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string WelcomeLogInLabel {
            get {
                return ResourceManager.GetString("WelcomeLogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SmartHomeWeb..
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are friends with {0}..
        /// </summary>
        public static string YouAreFriendsWith {
            get {
                return ResourceManager.GetString("YouAreFriendsWith", resourceCulture);
            }
        }
    }
}
