//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHomeWeb.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location has been registered!.
        /// </summary>
        public static string AddedLocationMessage {
            get {
                return ResourceManager.GetString("AddedLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been created. Thanks for registering!.
        /// </summary>
        public static string AddedPersonMessage {
            get {
                return ResourceManager.GetString("AddedPersonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string AddFriendButton {
            get {
                return ResourceManager.GetString("AddFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a friend.
        /// </summary>
        public static string AddFriendTitle {
            get {
                return ResourceManager.GetString("AddFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a location to your profile.
        /// </summary>
        public static string AddHasLocationPageTitle {
            get {
                return ResourceManager.GetString("AddHasLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register location.
        /// </summary>
        public static string AddLocationButtonText {
            get {
                return ResourceManager.GetString("AddLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to register a location..
        /// </summary>
        public static string AddLocationNotAuthenticatedText {
            get {
                return ResourceManager.GetString("AddLocationNotAuthenticatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new location..
        /// </summary>
        public static string AddLocationPageDescription {
            get {
                return ResourceManager.GetString("AddLocationPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register location.
        /// </summary>
        public static string AddLocationPageTitle {
            get {
                return ResourceManager.GetString("AddLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        public static string AddPersonButtonText {
            get {
                return ResourceManager.GetString("AddPersonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AddPersonPageTitle {
            get {
                return ResourceManager.GetString("AddPersonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All friends.
        /// </summary>
        public static string AllFriendsLabel {
            get {
                return ResourceManager.GetString("AllFriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birth date could not be parsed. Have you tried formatting it as &apos;YYYY/MM/DD&apos;?.
        /// </summary>
        public static string BadlyFormattedBirthDateError {
            get {
                return ResourceManager.GetString("BadlyFormattedBirthDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug pages.
        /// </summary>
        public static string DebugPagesTitle {
            get {
                return ResourceManager.GetString("DebugPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names must be non-empty..
        /// </summary>
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be non-empty..
        /// </summary>
        public static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames must be non-empty..
        /// </summary>
        public static string EmptyUserNameError {
            get {
                return ResourceManager.GetString("EmptyUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsPageTitle {
            get {
                return ResourceManager.GetString("FriendsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend&apos;s username.
        /// </summary>
        public static string FriendUsernameLabel {
            get {
                return ResourceManager.GetString("FriendUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pre-existing location called &apos;{0}&apos;..
        /// </summary>
        public static string LocationAlreadyExistsError {
            get {
                return ResourceManager.GetString("LocationAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string LocationNameLabel {
            get {
                return ResourceManager.GetString("LocationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationsPageTitle {
            get {
                return ResourceManager.GetString("LocationsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string MeasurementsPageTitle {
            get {
                return ResourceManager.GetString("MeasurementsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you entered did not match..
        /// </summary>
        public static string PasswordMismatchError {
            get {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PersonAddressLabel {
            get {
                return ResourceManager.GetString("PersonAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken. ಠ_ಠ.
        /// </summary>
        public static string PersonAlreadyExistsError {
            get {
                return ResourceManager.GetString("PersonAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string PersonBirthdateLabel {
            get {
                return ResourceManager.GetString("PersonBirthdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of residence.
        /// </summary>
        public static string PersonCityLabel {
            get {
                return ResourceManager.GetString("PersonCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PersonNameLabel {
            get {
                return ResourceManager.GetString("PersonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PersonPasswordLabel {
            get {
                return ResourceManager.GetString("PersonPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string PersonRepeatPasswordLabel {
            get {
                return ResourceManager.GetString("PersonRepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string PersonUserNameLabel {
            get {
                return ResourceManager.GetString("PersonUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string PersonZipCodeLabel {
            get {
                return ResourceManager.GetString("PersonZipCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a location:.
        /// </summary>
        public static string PickALocation {
            get {
                return ResourceManager.GetString("PickALocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SensorDescriptionLabel {
            get {
                return ResourceManager.GetString("SensorDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SensorIDLabel {
            get {
                return ResourceManager.GetString("SensorIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SensorLocationLabel {
            get {
                return ResourceManager.GetString("SensorLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SensorNameLabel {
            get {
                return ResourceManager.GetString("SensorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string SensorNotesLabel {
            get {
                return ResourceManager.GetString("SensorNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsPageTitle {
            get {
                return ResourceManager.GetString("SensorsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find your username in the database..
        /// </summary>
        public static string UserNameNotFoundError {
            get {
                return ResourceManager.GetString("UserNameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to view your friends..
        /// </summary>
        public static string ViewFriendsNotLoggedInError {
            get {
                return ResourceManager.GetString("ViewFriendsNotLoggedInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log, track, and organize your devices&apos; electricity usage. Create graphs of aggregated data and share them with friends..
        /// </summary>
        public static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string WelcomeCreateAccountButton {
            get {
                return ResourceManager.GetString("WelcomeCreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SmartHomeWeb..
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
