language: csharp
apt:
    - sqlite3
    - python3
solution: backend/SmartHomeWeb/SmartHomeWeb.sln
script:
    - xbuild /p:Configuration=Release backend/SmartHomeWeb/SmartHomeWeb.sln
    - nuget restore json-utils/json-utils.sln
    - xbuild /p:Configuration=Release json-utils/json-utils.sln
    - ./init-db.sh
