language: csharp
apt:
    packages:
        - sqlite3
        - python3
solution: backend/SmartHomeWeb/SmartHomeWeb.sln
# before_install:
#     - python3 -V
script:
    - xbuild /p:Configuration=Release backend/SmartHomeWeb/SmartHomeWeb.sln
    - python init-db.py
