// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SmartHomeWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartHomeWeb.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        public static string EmptyUserNameError {
            get {
                return ResourceManager.GetString("EmptyUserNameError", resourceCulture);
            }
        }
        
        public static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        public static string BadlyFormattedBirthDateError {
            get {
                return ResourceManager.GetString("BadlyFormattedBirthDateError", resourceCulture);
            }
        }
        
        public static string UserNameNotFoundError {
            get {
                return ResourceManager.GetString("UserNameNotFoundError", resourceCulture);
            }
        }
        
        public static string DebugPagesTitle {
            get {
                return ResourceManager.GetString("DebugPagesTitle", resourceCulture);
            }
        }
        
        public static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
        
        public static string LocationsPageTitle {
            get {
                return ResourceManager.GetString("LocationsPageTitle", resourceCulture);
            }
        }
        
        public static string SensorsPageTitle {
            get {
                return ResourceManager.GetString("SensorsPageTitle", resourceCulture);
            }
        }
        
        public static string MeasurementsPageTitle {
            get {
                return ResourceManager.GetString("MeasurementsPageTitle", resourceCulture);
            }
        }
        
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        public static string FriendsPageTitle {
            get {
                return ResourceManager.GetString("FriendsPageTitle", resourceCulture);
            }
        }
        
        public static string AddLocationPageTitle {
            get {
                return ResourceManager.GetString("AddLocationPageTitle", resourceCulture);
            }
        }
        
        public static string AddHasLocationPageTitle {
            get {
                return ResourceManager.GetString("AddHasLocationPageTitle", resourceCulture);
            }
        }
        
        public static string AddPersonPageTitle {
            get {
                return ResourceManager.GetString("AddPersonPageTitle", resourceCulture);
            }
        }
        
        public static string AddLocationPageDescription {
            get {
                return ResourceManager.GetString("AddLocationPageDescription", resourceCulture);
            }
        }
        
        public static string LocationNameLabel {
            get {
                return ResourceManager.GetString("LocationNameLabel", resourceCulture);
            }
        }
        
        public static string AddLocationButtonText {
            get {
                return ResourceManager.GetString("AddLocationButtonText", resourceCulture);
            }
        }
        
        public static string AddLocationNotAuthenticatedText {
            get {
                return ResourceManager.GetString("AddLocationNotAuthenticatedText", resourceCulture);
            }
        }
        
        public static string LocationAlreadyExistsError {
            get {
                return ResourceManager.GetString("LocationAlreadyExistsError", resourceCulture);
            }
        }
        
        public static string PersonAlreadyExistsError {
            get {
                return ResourceManager.GetString("PersonAlreadyExistsError", resourceCulture);
            }
        }
        
        public static string PasswordMismatchError {
            get {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }
        
        public static string AddedLocationMessage {
            get {
                return ResourceManager.GetString("AddedLocationMessage", resourceCulture);
            }
        }
        
        public static string AddedPersonMessage {
            get {
                return ResourceManager.GetString("AddedPersonMessage", resourceCulture);
            }
        }
        
        public static string PersonUserNameLabel {
            get {
                return ResourceManager.GetString("PersonUserNameLabel", resourceCulture);
            }
        }
        
        public static string PersonNameLabel {
            get {
                return ResourceManager.GetString("PersonNameLabel", resourceCulture);
            }
        }
        
        public static string PersonPasswordLabel {
            get {
                return ResourceManager.GetString("PersonPasswordLabel", resourceCulture);
            }
        }
        
        public static string PersonRepeatPasswordLabel {
            get {
                return ResourceManager.GetString("PersonRepeatPasswordLabel", resourceCulture);
            }
        }
        
        public static string PersonBirthdateLabel {
            get {
                return ResourceManager.GetString("PersonBirthdateLabel", resourceCulture);
            }
        }
        
        public static string PersonAddressLabel {
            get {
                return ResourceManager.GetString("PersonAddressLabel", resourceCulture);
            }
        }
        
        public static string PersonCityLabel {
            get {
                return ResourceManager.GetString("PersonCityLabel", resourceCulture);
            }
        }
        
        public static string PersonZipCodeLabel {
            get {
                return ResourceManager.GetString("PersonZipCodeLabel", resourceCulture);
            }
        }
        
        public static string AddPersonButtonText {
            get {
                return ResourceManager.GetString("AddPersonButtonText", resourceCulture);
            }
        }
    }
}
