// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SmartHomeWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartHomeWeb.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        public static string DebugPagesTitle {
            get {
                return ResourceManager.GetString("DebugPagesTitle", resourceCulture);
            }
        }
        
        public static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
        
        public static string LocationsPageTitle {
            get {
                return ResourceManager.GetString("LocationsPageTitle", resourceCulture);
            }
        }
        
        public static string SensorsPageTitle {
            get {
                return ResourceManager.GetString("SensorsPageTitle", resourceCulture);
            }
        }
        
        public static string MeasurementsPageTitle {
            get {
                return ResourceManager.GetString("MeasurementsPageTitle", resourceCulture);
            }
        }
        
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        public static string FriendsPageTitle {
            get {
                return ResourceManager.GetString("FriendsPageTitle", resourceCulture);
            }
        }
    }
}
